spring.datasource.url=jdbc:postgresql://localhost:5432/studs
spring.datasource.username=s409658
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.main.allow-bean-definition-overriding=true
server.port=4240